remote_theme: pmarsceill/just-the-docs
title: Xenlism Wildfire for Sailfish OS
description: Xenlism Wildfire for Sailfish OS
baseurl: ""
exclude: ["appicons/", "other/", "qml/", "rpm/", "scripts/", "src/", "theme/", "translations/", "LICENSE", "*.desktop", "*.pro"]

url: "https://uithemer.github.io/harbour-themepack-xenlism-wildfire"
search_enabled: false
aux_links:
    "Xenlism Wildfire on GitHub":
      - "//github.com/uithemer/harbour-themepack-xenlism-wildfire"
