remote_theme: pmarsceill/just-the-docs
title: My Data Transfer
description: Backup and transfer app data, documents, music, pictures and videos.
baseurl: ""
exclude: ["appicons/", "other/", "qml/", "rpm/", "scripts/", "src/", "theme/", "translations/", "LICENSE", "*.desktop", "*.pro"]

url: "https://fravaccaro.github.io/harbour-mydatatransfer"
search_enabled: false
aux_links:
    "My Data Transfer on GitHub":
      - "//github.com/fravaccaro/harbour-mydatatranfser"
